### ISSUE TITLE
Does not work with multiple specs

### ISSUE THREAD

**Issue by Stanzilla** [Phanx/PhanxBind#1]
Bindings will overwrite/get lost on spec switch.

**Comment by Bornabe** [comment]
I just found this addon and would LOVE to see this added.  I'm using this with Clique and as a Druid wanted to set my Main form as Mouse Button 5, a Shift Mouse Button 5 for Cat Form, etc... and it's so awesome!  Works great with Clique for onHover of Unit Frames for Clique and everywhere else for PhanxBind, same buttons used!  If we could have spec profile swapping similar to how Clique does it, it would be a HUGE improvement for keybinding.

Phanx, you have some of the best addons in existence, thanks man!

**Comment by Phanx** [comment]
Oops, forgot about this. I wrote the code and it seemed to be working in my limited testing, but it's not released yet. If you want to try it:

1. Back up your existing settings (easiest way, just backup the whole WTF folder)
2. Download this version: https://github.com/phanx-wow/PhanxBind/archive/a73f31e064b3d255f23477aa3242386c416332ae.zip
3. Copy the files over the top of your installed version
4. Reload your UI, or relog.

You'll see lots of spammy debug messages in your main chat frame. If something goes wrong, report back with [the message contents](https://www.curseforge.com/wow/addons/chat_copy) (or at least screenshots of them). If nothing goes wrong, report back and let me know.

**Comment by Maximos7** [comment]
I didn't get this? Is it working with spec changes or not cause i just installed it and it doesnt...:/

**Comment by Phanx** [comment]
This was added in version 7.3.5.1. If you're seeing some problem with it please post a new issue and describe the problem in detail (e.g. actions you performed, what you expected to happen, what actually happened, copy of your saved variables file, what class/specs were involved, etc.)
